### PR TITLE
liblrs: add more members and split admin

### PR DESCRIPTION
**Pull request by Tristramg**

### CODE REVIEW

**Review by flomonster — APPROVED** [review]
LGTM, You might want to adapt the `.github/CODEOWNERS` file to authorize liblrs-admins group to approve change to this file.

**Review by mxmehl — DISMISSED** [review]
LGTM. Just three comments:

1. As @flomonster said, adding this file and the admin team to CODEOWNERS makes sense
2. The `maintainer` group isn't really necessary as the member organisation happens via this file, and all manual changes will be overridden anyway.
3. You can also make the team names pretty-printed, e.g. "liblrs Admins", if you prefer.

**Comment by flomonster** [comment]
Yes, that's enough. The problem is that your team hasn't been created yet, since the PR hasn't been merged. So GitHub warns you that a team in your CODEOWNERS doesn't exist (yet).

**Review by flomonster — APPROVED** [review]
LGTM

**Review by mxmehl — APPROVED** [review]

**Pull request merged**
